M48
; DRILL file {KiCad 7.0.1-0} date 2023 March 23, Thursday 13:45:07
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-03-23T13:45:07+11:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.1-0
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X4.487Y-3.837
X4.537Y-1.937
X6.537Y-2.537
X6.537Y-3.637
T0
M30
